name: ci-cd workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: github-actions-451404
  REGION: asia-south1
  GAR_LOCATION: asia-south1-docker.pkg.dev/github-actions-451404/github-actions-registry
  SERVICE_ACCOUNT_EMAIL: github-actions-assignment@github-actions-451404.iam.gserviceaccount.com
  APP_NAME: github-assignment-app


jobs:
  # Testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v3
  #     - name: Setup the node enviroment
  #       uses: actions/setup-node@v2
  #       with: 
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run the test
  #       run: npm test

  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
      
      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}/backend:${{ github.sha }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}/backend:${{ github.sha }}

  Deploy-to-cloud-run:
    needs: build-and-push-to-gcr
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP_NAME }} \
            --region ${{ env.REGION }} \
            --image ${{ env.GAR_LOCATION }}/backend:${{ github.sha }} \
            --platform "managed" \
            --service-account ${{ env.SERVICE_ACCOUNT_EMAIL }} \
            --port 8080 \ 
            --quiet