name: ci-cd workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: github-actions-451404
  REGION: asia-south1
  GAR_LOCATION: asia-south1-docker.pkg.dev/github-actions-451404/github-actions-registry

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup the node enviroment
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run the test
        run: npm test
  build-and-push-to-gcr:
    needs: Testing
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      
      
      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}/backend

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}/backend