name: ci-cd workflow

on:
  push:
    branches:
      - main

jobs:
  # Testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v3
  #     - name: Setup the node enviroment
  #       uses: actions/setup-node@v2
  #       with: 
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run the test
  #       run: npm test
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Google Artifact Registry Build & Push
        uses: piotrkrusinski/action-google-artifact-registry@[version tag] # Replace with a specific tag like v1.0.0
        with:
          google_project_id: github-actions-451404
          google_artifact_registry_region: asia-south1
          google_artifact_registry_hostname: asia-south1-docker.pkg.dev
          google_artifact_registry_name: github-actions-registry
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_BASE64 }} # See explanation below
          dockerfile: ./Dockerfile # Or the path to your Dockerfile
          image_name: my-image-name # Choose a descriptive name for your image
          tag_list: version_1.0 master 20231024_123456 # Or use ${{ github.sha }} for the commit SHA
          build_args: "" # Add any build arguments if needed (e.g., ARG VERSION=1.2.3)