name: ci-cd workflow

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup the node enviroment
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run the test
        run: npm test
  Build-Docker-Image:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/cloudrun/backend-server:v1
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}