name: ci-cd workflow

on:
  push:
    branches:
      - main

jobs:
  # Testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v3
  #     - name: Setup the node enviroment
  #       uses: actions/setup-node@v2
  #       with: 
  #         node-version: 18
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run the test
  #       run: npm test
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.2-rootless # Or latest

      - name: Login
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Test gcloud
        run: gcloud auth list

      - name: Configure Docker for GAR
        run: gcloud auth activate-service-account --key-file=project.json

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # If your Dockerfile is not named "Dockerfile" or not in the root directory
          tags: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.GOOGLE_ARTIFACT_REGISTRY_NAME }}:${{ github.sha }}
          push: true
          cache-from: type=local,dest=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max